import "./globals.css";
//import { Inter } from "next/font/google";
import Providers from "../utils/providers.jsx";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{ fontFamily: "Aleo-Regular" }}
        className={/* inter.className +*/ " grid grid-flow-row "}
      >
        <Providers>
          <Header />
          <main className="  min-h-screen ">
            {children}
            <ReactQueryDevtools />
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
